version: '3.7'

services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: unless-stopped
    volumes:
      - ./db_data:/var/lib/mysql
      - ./db_dump:/docker-entrypoint-initdb.d
    ports:
      - "8025:3306"
    networks:
      local:
        ipv4_address: 172.28.6.4

  wordpress:
    image: wordpress:latest
    restart: unless-stopped
    ports:
      - "8026:80"
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - type: volume
        source: app_data
        target: /var/www/html
    networks:
      local:
        ipv4_address: 172.28.6.5

volumes:
  app_data:
    driver: local
    driver_opts:
      type: none
      device: "${PWD}/src"
      o: bind

networks:
  local:
    ipam:
      driver: default
      config:
        - subnet: 172.28.6.0/24
